default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  pool: 5

development:
  <<: *default
  database: stats_dev
  username: postgres
  password:

test:
  <<: *default
  database: stats_test

production:
  <<: *default
  database: stats_prod
  username: stats
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>